### ISSUE TITLE
Cross compile failed, unable to find library -llog

### ISSUE THREAD

**Issue by uuhan** [rustls/rustls-platform-verifier#153]
How to compile this crate to aarch64-linux-android?

```bash
cargo build --target=aarch64-linux-android
```

failed with：
```text
  = note: ld: error: unable to find library -llog
          collect2: error: ld returned 1 exit status
```

**Comment by complexspaces** [comment]
Hi there,

I'm not sure what your build configuration looks like but you will need to use a tool like [cargo-ndk](https://github.com/bbqsrc/cargo-ndk) that injects the proper Android NDK (from the SDK) library search paths into the build process. Otherwise, Rust and Cargo have no idea where to look for Android-specific libraries. Specifically in your example I think the linker is failing to find the Android logging NDK headers.

I will say that I don't know exactly why this is appearing for you since the `android_logger` crate is only a dependency via `ffi-testing`, which isn't intended for end users.

**Comment by uuhan** [comment]
> Hi there,
> 
> I'm not sure what your build configuration looks like but you will need to use a tool like [cargo-ndk](https://github.com/bbqsrc/cargo-ndk) that injects the proper Android NDK (from the SDK) library search paths into the build process. Otherwise, Rust and Cargo have no idea where to look for Android-specific libraries. Specifically in your example I think the linker is failing to find the Android logging NDK headers.
> 
> I will say that I don't know exactly why this is appearing for you since the `android_logger` crate is only a dependency via `ffi-testing`, which isn't intended for end users.

Thanks for your reply. You are right the cargo-ndk works well with the cross compilation.
