### ISSUE TITLE
Invalid Java package name

### ISSUE THREAD

**Issue by jonduran3000** [rustls/rustls-platform-verifier#18]
Currently, the Android library uses a package name of `com.onepassword.rustls-platform-verifier`, which works fine on older versions of Java but on newer versions of Java presents us with this build failure:

> Package 'rustls.rustls-platform-verifier' from AndroidManifest.xml is not a valid Java package name as 'rustls-platform-verifier' is not a valid Java identifier.

Underscores are not considered valid characters in a Java identifier.

**Suggestion:** change the package name to something like `rustls.platformverifier.android` (not sure why 1Password needs to be referenced at all) and remove all of the underscores.

This is currently blocking some Android updates at 1Password so I'm happy to make this change but I just wanted to file an issue so that this is being tracked.

**Comment by complexspaces** [comment]
Thanks for filing this. This seems like a pretty easy change to make, but please feel free to make a PR if you'd like. Otherwise I can get to this next week.

> not sure why 1Password needs to be referenced at all

Its a holdover from when this crate was moved from the `1Password` GitHub organization to here. At the time no one saw it as an issue to keep it as-is, so it wasn't modified. This seems like a good opportunity to fix it though.
